- hosts: servers
  become: yes
  tasks:
    - name: Actualizar cache de software de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar Cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear archivo
      file:
        path: /home/vagrant/archivo.txt
        state: touch

    - name: Copiar archivos
      copy:
        src: /local/path/archivo.txt
        dest: /home/vagrant/archivo.txt

    - name: Crear carpetas
      file:
        path: /home/vagrant/carpeta
        state: directory

    - name: Iniciar servicio Apache
      service:
        name: apache2
        state: started

    - name: Agregar usuario al servidor
      user:
        name: nuevo_usuario
        state: present

    - name: Ejecutar script en el servidor
      command: /path/to/script.sh
